# Generated by Django 3.1 on 2021-03-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_api', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_account', models.CharField(max_length=32, unique=True)),
                ('u_id', models.CharField(max_length=256)),
                ('u_password', models.CharField(max_length=30)),
                ('u_authority', models.CharField(max_length=256)),
                ('u_department', models.CharField(max_length=30)),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('u_telephone', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
