# Generated by Django 3.1 on 2021-03-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_api', '0003_auto_20210301_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.CharField(default='sf1234', max_length=30),
        ),
    ]
